### ISSUE TITLE
Compatiblity with React v16.x

### ISSUE THREAD

**Issue by toxicgorilla** [michaellyons/react-launch-gauge#4]
Hi,

I keep getting the following two warnings in my build, relating to react-launch-guage:

warning " > react-launch-gauge@0.2.3" has incorrect peer dependency "react@^15.5.4".
warning " > react-launch-gauge@0.2.3" has incorrect peer dependency "react-dom@^15.5.4".

We have upgraded our project to React 16.x. and your plugin works fine! Specifically, we have:
"react": "16.3.2"
"react-dom": "16.3.2"

Would you be happy for me to send you a PR, with a change to package.json upgrading the peerDependecies?

Thanks,

Steve

**Comment by michaellyons** [comment]
Absolutely yes please,

I've sadly neglected this project over the last year, I will redeem this taking some time to look into future-proofing the component for 16.3 and 17.0 in the next few weeks,

Sorry for not doing so previously.

**Comment by toxicgorilla** [comment]
Thanks for accepting my PR. Any chance you could do a 0.2.4 release to NPM?

**Comment by michaellyons** [comment]
Yes I just now ran an NPM publish, forgot that I had to do that after the PR lol

**Comment by toxicgorilla** [comment]
thanks!
